// settings.gradle.kts

pluginManagement {
    repositories {
        // המאגרים מוגדרים ישירות בתוך repositories{}
        // כדי לוודא ש-Gradle יכול למצוא את פלאגין האנדרואיד (AGP)
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

// settings.gradle.kts
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral() // חובה שיופיע לפני jitpack
        maven { url 'https://jitpack.io' }
    }
}

rootProject.name = "Smart-Credit-Card-Transaction-Analysis"
include ':app'